### ISSUE TITLE
the query call in /php/login.php isn't checked for errors

### ISSUE THREAD

**Issue by divinity76** [Nesseref/nginx-rtmp-auth#5]
.. which may result in erroneously giving bool(false) to mysqli_num_rows. best way to check for errors is to do `mysqli_report(MYSQLI_REPORT_ALL);`

**Comment by xnite** [comment]
should be fixed in https://github.com/Nesseref/nginx-rtmp-auth/commit/602f4f390c603105ac758910207cf76c261e3ec3

**Comment by divinity76** [comment]
... PS, the MySQLi api was never deprecated. you're thinking about the mysql_ api. although, the only good reason to use mysqli over PDO is if you're using MYSQLI_ASYNC , which makes MySQLi significantly faster than PDO.  - but since you weren't using that anyway, they're more or less equal

**Comment by divinity76** [comment]
@xnite ... PS, the MySQLi api was never deprecated. you're thinking about the mysql_ api. big difference. although, the only good reason to use mysqli over PDO is if you're using MYSQLI_ASYNC , which makes MySQLi significantly faster than PDO. - but since you weren't using that anyway, they're more or less equal (PDO has no support for async queries)

**Comment by xnite** [comment]
You're correct, I was wrong. I was doing more research today on what's been removed from PHP7 and mysqli wasn't it, it was just ext/mysql as you said. But at least now the statements are prepared.
