### ISSUE TITLE
Not using prepared statements

### ISSUE THREAD

**Issue by xnite** [Nesseref/nginx-rtmp-auth#7]
This code is using deprecated functions for MySQL queries. You should be using the PDO driver with prepared statements. If you would like I could convert the code over and make a pull request.

**Comment by Nesseref** [comment]
Sure, it'd be appreciated.

**Comment by xnite** [comment]
cool I went ahead and made a pull request. Everything has been converted to PDO drivers which will be compatible with PHP7. Once you accept it you can close this issue. I'll work on some of the other issues at some point as well.
